pipeline {
  agent none
  environment {
    PM_API_TOKEN_ID = credentials('pm-api-token-id')
    PM_API_TOKEN_SECRET = credentials('pm-api-token-secret')
  }
  stages {
    stage('init') {
      agent {
        docker {
          image 'hashicorp/terraform:1.9.8'
          args '--entrypoint=""'
        }
      }
      steps {
        dir('kubernetes/02_kubernetes_production_ready/terraform') {
          sh '''
            terraform init -no-color
          '''
        }
      }
    }
    stage('plan') {
      agent {
        docker {
          image 'hashicorp/terraform:1.9.8'
          args '--entrypoint=""'
        }
      }
      steps {
        dir('kubernetes/02_kubernetes_production_ready/terraform') {
          withCredentials([string(credentialsId: 'mateus-public-key', variable: 'MATEUS_PUBLIC_KEY')]) {
            sh '''
              echo "$MATEUS_PUBLIC_KEY" > id_rsa.pub
              terraform plan -no-color
            '''
          }
        }
      }
    }
  }
}
